apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-my
  description: My own Team
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-my@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: lihongbjmy 
spec:
  profile:
    displayName: lihongbjmy 
    email: lihongbjmy@cn.ibm.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [team-a, team-my]

